### ISSUE TITLE
sed: RE error: illegal byte sequence

### ISSUE THREAD

**Issue by dpfaffenbauer** [DivanteLtd/anonymizer#18] opened 2018-07-24 14:04 UTC
Getting this error on import and export, not sure how. Removing it helps though

**Comment by mkoszutowski** [comment] 2018-07-25 06:33
@dpfaffenbauer Can you put here full stack trace from this issue?

**Comment by dpfaffenbauer** [comment] 2018-07-25 06:34
@mkoszutowski I am sorry, don't have it anymore. If it helps, I used a Pimcore 5 Database.

**Comment by mkoszutowski** [comment] 2018-07-25 06:39
Thanks for the info. I will try to reproduce that with default Pimcore 5 database.

**Comment by mkoszutowski** [comment] 2018-08-01 06:40
[pimcore_5_sample.sql.gz](https://github.com/DivanteLtd/anonymizer/files/2248300/pimcore_5_sample.sql.gz)
Newest Pimcore 5 database dump

**Comment by mkoszutowski** [comment] 2018-08-01 09:13
I have added to repo test for Pimcore 5, for the newest database dump (this above) everything works fine. Because of I can't reproduce this issue I close it.

**Closed by mkoszutowski** 2018-08-01 09:13 UTC
